# Generated by Django 4.0.6 on 2022-08-12 05:42

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMap_Image',
            fields=[
                ('image_ID', models.TextField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='map_image', verbose_name='子標題圖片1 URL')),
            ],
        ),
    ]
