# Generated by Django 4.0.6 on 2022-08-12 06:12

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pic_url',
            field=models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='map_image', verbose_name='子標題圖片1 URL'),
        ),
    ]
