# Generated by Django 4.0.6 on 2022-08-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_question_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
    ]
