# Generated by Django 4.0.6 on 2022-08-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_remove_question_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Map_Image',
        ),
    ]
