# Generated by Django 4.0.6 on 2022-08-15 07:28

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_delete_googlemap_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_image',
            name='pic_url',
            field=models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='map_image', verbose_name='圖片URL'),
        ),
    ]
