# Generated by Django 4.0.6 on 2022-08-16 07:00

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_map_image_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名稱')),
                ('logo', models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='', verbose_name='公司logo')),
                ('bottom_title', models.CharField(blank=True, max_length=20, verbose_name='底部標題')),
                ('bottom_content', models.TextField(blank=True, max_length=300, verbose_name='底部內容')),
                ('bottom_email', models.CharField(blank=True, max_length=100, verbose_name='底部email')),
                ('bottom_phone', models.CharField(blank=True, max_length=50, verbose_name='底部連絡電話')),
            ],
        ),
    ]
