# Generated by Django 4.0.6 on 2022-08-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_mappage_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('job_title', models.CharField(max_length=80, verbose_name='職稱')),
            ],
        ),
    ]
