# Generated by Django 4.0.6 on 2022-09-02 02:54

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_visitor_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappage',
            name='form_image',
            field=models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='map_image', verbose_name='表單底部圖片URL'),
        ),
        migrations.AddField(
            model_name='mappage',
            name='form_title',
            field=models.TextField(blank=True, max_length=100, verbose_name='表單頂部內容'),
        ),
        migrations.AddField(
            model_name='mappage_en',
            name='form_title',
            field=models.TextField(blank=True, max_length=300, verbose_name='表單頂部內容'),
        ),
    ]
