# Generated by Django 4.0.6 on 2022-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_mappage_form_image_mappage_form_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_info',
            name='job_title',
            field=models.CharField(max_length=80, verbose_name='隸屬單位'),
        ),
    ]
