# Generated by Django 4.0.6 on 2022-09-02 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_visitor_info_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_info',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
