# Generated by Django 4.0.6 on 2022-09-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_visitor_info_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_info',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='傳送日期'),
        ),
    ]
