# Generated by Django 4.0.6 on 2022-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=200, verbose_name='內容'),
        ),
    ]
