# Generated by Django 4.0.6 on 2022-08-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic_url',
            field=models.ImageField(blank=True, upload_to='post_detail/', verbose_name='圖片URL'),
        ),
    ]
