# Generated by Django 4.0.6 on 2022-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_adress_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bottom_content',
            field=models.TextField(blank=True, max_length=300, verbose_name='底部內容'),
        ),
        migrations.AddField(
            model_name='contact',
            name='bottom_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='底部email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='bottom_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='底部連絡電話'),
        ),
        migrations.AddField(
            model_name='contact',
            name='bottom_title',
            field=models.CharField(blank=True, max_length=20, verbose_name='底部標題'),
        ),
    ]
