# Generated by Django 4.0.6 on 2022-08-16 07:36

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_bottom_content_contact_bottom_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='logo',
            field=models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='', verbose_name='公司logo'),
        ),
    ]
