# Generated by Django 4.0.6 on 2022-08-23 06:06

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名稱')),
                ('logo', models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='', verbose_name='公司logo')),
                ('title', models.CharField(max_length=20, verbose_name='標題')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話:')),
                ('email', models.CharField(blank=True, max_length=60, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, max_length=100, verbose_name='地址')),
                ('office_hour', models.CharField(blank=True, max_length=60, verbose_name='辦公時間')),
                ('bottom_title', models.CharField(blank=True, max_length=20, verbose_name='底部標題')),
                ('bottom_content', models.TextField(blank=True, max_length=300, verbose_name='底部內容')),
                ('bottom_email', models.CharField(blank=True, max_length=100, verbose_name='底部email')),
                ('bottom_phone', models.CharField(blank=True, max_length=50, verbose_name='底部連絡電話')),
            ],
        ),
    ]
