# Generated by Django 4.0.6 on 2022-08-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_contact_en_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_en',
            name='address',
            field=models.TextField(blank=True, max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='contact_en',
            name='bottom_content',
            field=models.TextField(blank=True, max_length=400, verbose_name='底部內容'),
        ),
        migrations.AlterField(
            model_name='contact_en',
            name='bottom_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='底部標題'),
        ),
        migrations.AlterField(
            model_name='contact_en',
            name='name',
            field=models.CharField(max_length=50, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='contact_en',
            name='title',
            field=models.CharField(max_length=50, verbose_name='標題'),
        ),
    ]
