# Generated by Django 4.0.6 on 2022-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_en_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tax_ID_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='統一編號'),
        ),
        migrations.AddField(
            model_name='contact_en',
            name='tax_ID_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='統一編號'),
        ),
    ]
