# Generated by Django 4.0.6 on 2022-08-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_experience_title_alter_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司名稱')),
                ('title1', models.CharField(max_length=50, verbose_name='主題名稱1')),
                ('title2', models.CharField(max_length=50, verbose_name='主題名稱2')),
            ],
        ),
    ]
