# Generated by Django 4.0.6 on 2022-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_title_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='標題')),
                ('content', models.TextField(blank=True, max_length=1500, verbose_name='內容')),
            ],
        ),
        migrations.CreateModel(
            name='Service_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='標題')),
                ('content', models.TextField(blank=True, max_length=1500, verbose_name='內容')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Title_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司名稱')),
                ('title1', models.CharField(max_length=50, verbose_name='主題名稱1')),
                ('title2', models.CharField(max_length=50, verbose_name='主題名稱2')),
                ('bottom_title', models.CharField(blank=True, max_length=40, verbose_name='底部標題')),
                ('bottom_content', models.TextField(blank=True, max_length=500, verbose_name='底部內容')),
                ('bottom_email', models.CharField(blank=True, max_length=100, verbose_name='底部email')),
                ('bottom_phone', models.CharField(blank=True, max_length=100, verbose_name='底部連絡電話')),
            ],
        ),
    ]
