# Generated by Django 4.0.6 on 2022-10-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_experience_content_alter_experience_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='pic_url',
        ),
    ]
