# Generated by Django 4.0.6 on 2022-10-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_experience_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSTC_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='計畫')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
            ],
        ),
        migrations.CreateModel(
            name='NSTC_project_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='計畫')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
            ],
        ),
    ]
