# Generated by Django 4.0.6 on 2022-08-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
