# Generated by Django 4.0.6 on 2022-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid_on_map',
            name='geom',
            field=models.JSONField(),
        ),
    ]
