# Generated by Django 4.0.6 on 2022-08-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_grid_on_map_geom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid_on_map',
        ),
    ]
