# Generated by Django 4.0.6 on 2022-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0009_delete_grid_on_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名稱')),
                ('big_pic_url1', models.ImageField(blank=True, upload_to='home_image/', verbose_name='圖片1 URL')),
                ('big_pic_url2', models.ImageField(blank=True, upload_to='home_image/', verbose_name='圖片2 URL')),
                ('big_pic_url3', models.ImageField(blank=True, upload_to='home_image/', verbose_name='圖片3 URL')),
                ('title', models.CharField(max_length=20, verbose_name='標題')),
                ('title_content', models.TextField(max_length=200, verbose_name='標題內容')),
                ('sub_title1', models.CharField(max_length=50, verbose_name='子標題1')),
                ('sub_title2', models.CharField(max_length=50, verbose_name='子標題2')),
                ('sub_title3', models.CharField(max_length=50, verbose_name='子標題3')),
                ('sub_title4', models.CharField(max_length=50, verbose_name='子標題4')),
                ('content1', models.TextField(max_length=200, verbose_name='子標題內容1')),
                ('content2', models.TextField(max_length=200, verbose_name='子標題內容2')),
                ('content3', models.TextField(max_length=200, verbose_name='子標題內容3')),
                ('content4', models.TextField(max_length=200, verbose_name='子標題內容4')),
                ('pic_url', models.ImageField(blank=True, upload_to='post_detail/', verbose_name='子標題圖片4 URL')),
            ],
        ),
    ]
