# Generated by Django 4.0.6 on 2022-08-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='pic_url',
            new_name='pic_url4',
        ),
        migrations.AddField(
            model_name='homepage',
            name='pic_url1',
            field=models.ImageField(blank=True, upload_to='post_detail/', verbose_name='子標題圖片1 URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pic_url2',
            field=models.ImageField(blank=True, upload_to='post_detail/', verbose_name='子標題圖片2 URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pic_url3',
            field=models.ImageField(blank=True, upload_to='post_detail/', verbose_name='子標題圖片3 URL'),
        ),
    ]
