# Generated by Django 4.0.6 on 2022-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_pic_url_homepage_pic_url4_homepage_pic_url1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMap_img',
            fields=[
                ('image_ID', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='圖片ID')),
                ('pic_url1', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片1 URL')),
                ('pic_url2', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片2 URL')),
                ('pic_url3', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片3 URL')),
                ('pic_url4', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片4 URL')),
                ('pic_url5', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片5 URL')),
                ('pic_url6', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片6 URL')),
                ('pic_url7', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片7 URL')),
                ('pic_url8', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片8 URL')),
                ('pic_url9', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片9 URL')),
                ('pic_url0', models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片10 URL')),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='pic_url1',
            field=models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片1 URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='pic_url2',
            field=models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片2 URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='pic_url3',
            field=models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片3 URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='pic_url4',
            field=models.ImageField(blank=True, upload_to='home_image/', verbose_name='子標題圖片4 URL'),
        ),
    ]
