# Generated by Django 4.0.6 on 2022-08-08 12:10

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_googlemap_img_pic_url0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='pic_url1',
            field=models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='home_image/', verbose_name='子標題圖片1 URL'),
        ),
    ]
