# Generated by Django 4.0.6 on 2022-08-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_googlemap_img_image_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleMap_img',
        ),
    ]
