# Generated by Django 4.0.6 on 2022-08-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_googlemap_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content4',
        ),
    ]
