# Generated by Django 4.0.6 on 2022-08-16 06:46

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_homepage_content1_remove_homepage_content2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='', verbose_name='公司logo'),
        ),
    ]
