# Generated by Django 4.0.6 on 2022-08-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homepage_bottom_content_homepage_bottom_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名稱')),
                ('title', models.CharField(max_length=20, verbose_name='標題')),
                ('title_content', models.TextField(max_length=200, verbose_name='標題內容')),
                ('sub_title1', models.CharField(blank=True, max_length=50, verbose_name='子標題1')),
                ('sub_title2', models.CharField(blank=True, max_length=50, verbose_name='子標題2')),
                ('sub_title3', models.CharField(blank=True, max_length=50, verbose_name='子標題3')),
                ('sub_title4', models.CharField(blank=True, max_length=50, verbose_name='子標題4')),
                ('bottom_title', models.CharField(blank=True, max_length=20, verbose_name='底部標題')),
                ('bottom_content', models.TextField(blank=True, max_length=300, verbose_name='底部內容')),
                ('bottom_email', models.CharField(blank=True, max_length=100, verbose_name='底部email')),
                ('bottom_phone', models.CharField(blank=True, max_length=50, verbose_name='底部連絡電話')),
            ],
        ),
    ]
