# Generated by Django 4.0.6 on 2022-08-11 08:31

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名稱')),
                ('title', models.CharField(max_length=20, verbose_name='標題')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='內容')),
                ('member_title', models.CharField(max_length=20, verbose_name='成員標題')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='成員名稱')),
                ('pic_url', models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='AboutUs_image/', verbose_name='成員照片URL')),
                ('experience1', models.CharField(blank=True, max_length=30, verbose_name='經歷1')),
                ('experience2', models.CharField(blank=True, max_length=30, verbose_name='經歷2')),
                ('experience3', models.CharField(blank=True, max_length=30, verbose_name='經歷3')),
                ('experience4', models.CharField(blank=True, max_length=30, verbose_name='經歷4')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='連絡電話')),
                ('introduce', models.TextField(blank=True, max_length=200, verbose_name='成員介紹')),
            ],
        ),
    ]
