# Generated by Django 4.0.6 on 2022-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontent',
            name='phone',
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='content',
            field=models.TextField(blank=True, max_length=200, verbose_name='內容'),
        ),
    ]
