# Generated by Django 4.0.6 on 2022-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_aboutcontent_phone_aboutcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='introduce',
            field=models.TextField(blank=True, max_length=500, verbose_name='成員介紹'),
        ),
    ]
