# Generated by Django 4.0.6 on 2022-08-16 07:28

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_member_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='bottom_content',
            field=models.TextField(blank=True, max_length=300, verbose_name='底部內容'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='bottom_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='底部email'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='bottom_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='底部連絡電話'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='bottom_title',
            field=models.CharField(blank=True, max_length=20, verbose_name='底部標題'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='logo',
            field=models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='', verbose_name='公司logo'),
        ),
    ]
