# Generated by Django 4.0.6 on 2022-08-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutcontent_bottom_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名稱')),
                ('title', models.CharField(max_length=20, verbose_name='標題')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='內容')),
                ('member_title', models.CharField(max_length=50, verbose_name='成員標題')),
                ('bottom_title', models.CharField(blank=True, max_length=50, verbose_name='底部標題')),
                ('bottom_content', models.TextField(blank=True, max_length=400, verbose_name='底部內容')),
                ('bottom_email', models.CharField(blank=True, max_length=100, verbose_name='底部email')),
                ('bottom_phone', models.CharField(blank=True, max_length=50, verbose_name='底部連絡電話')),
            ],
        ),
        migrations.CreateModel(
            name='Member_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='成員名稱')),
                ('experience1', models.CharField(blank=True, max_length=100, verbose_name='經歷1')),
                ('experience2', models.CharField(blank=True, max_length=100, verbose_name='經歷2')),
                ('experience3', models.CharField(blank=True, max_length=100, verbose_name='經歷3')),
                ('experience4', models.CharField(blank=True, max_length=100, verbose_name='經歷4')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='連絡電話')),
                ('introduce', models.TextField(blank=True, max_length=700, verbose_name='成員介紹')),
            ],
        ),
    ]
