# Generated by Django 4.0.6 on 2022-08-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_aboutcontent_en_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent_en',
            name='content',
            field=models.TextField(blank=True, max_length=2000, verbose_name='內容'),
        ),
    ]
