# Generated by Django 4.0.6 on 2022-08-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_aboutcontent_en_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_en',
            name='experience1',
            field=models.CharField(blank=True, max_length=200, verbose_name='經歷1'),
        ),
        migrations.AlterField(
            model_name='member_en',
            name='experience2',
            field=models.CharField(blank=True, max_length=200, verbose_name='經歷2'),
        ),
        migrations.AlterField(
            model_name='member_en',
            name='experience3',
            field=models.CharField(blank=True, max_length=200, verbose_name='經歷3'),
        ),
        migrations.AlterField(
            model_name='member_en',
            name='experience4',
            field=models.CharField(blank=True, max_length=200, verbose_name='經歷4'),
        ),
        migrations.AlterField(
            model_name='member_en',
            name='introduce',
            field=models.TextField(blank=True, max_length=1200, verbose_name='成員介紹'),
        ),
    ]
