# Generated by Django 4.0.6 on 2022-10-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_member_en_experience1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='content',
            field=models.TextField(blank=True, max_length=600, verbose_name='內容'),
        ),
    ]
