# Generated by Django 4.0.6 on 2022-10-11 01:25

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='委託單位')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='標題')),
                ('content', models.TextField(blank=True, max_length=1500, verbose_name='內容')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司名稱')),
                ('logo', models.ImageField(blank=True, storage=home.models.OverwriteStorage(), upload_to='', verbose_name='公司logo')),
                ('title1', models.CharField(max_length=50, verbose_name='主題名稱1')),
                ('title2', models.CharField(max_length=50, verbose_name='主題名稱2')),
                ('bottom_title', models.CharField(blank=True, max_length=20, verbose_name='底部標題')),
                ('bottom_content', models.TextField(blank=True, max_length=300, verbose_name='底部內容')),
                ('bottom_email', models.CharField(blank=True, max_length=100, verbose_name='底部email')),
                ('bottom_phone', models.CharField(blank=True, max_length=50, verbose_name='底部連絡電話')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_Title_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司名稱')),
                ('title1', models.CharField(max_length=50, verbose_name='主題名稱1')),
                ('title2', models.CharField(max_length=50, verbose_name='主題名稱2')),
                ('bottom_title', models.CharField(blank=True, max_length=40, verbose_name='底部標題')),
                ('bottom_content', models.TextField(blank=True, max_length=500, verbose_name='底部內容')),
                ('bottom_email', models.CharField(blank=True, max_length=100, verbose_name='底部email')),
                ('bottom_phone', models.CharField(blank=True, max_length=100, verbose_name='底部連絡電話')),
            ],
        ),
        migrations.CreateModel(
            name='NSTC_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='計畫')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
            ],
        ),
        migrations.CreateModel(
            name='NSTC_project_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='計畫')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
            ],
        ),
    ]
