# Generated by Django 4.0.6 on 2022-10-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_experience_title_title1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience_title',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='experience_title_en',
            name='title2',
        ),
    ]
