# Generated by Django 4.0.6 on 2022-10-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_remove_experience_title_title2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience_title',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='experience_title_en',
            name='title1',
        ),
        migrations.AddField(
            model_name='experience_title',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='主題名稱'),
        ),
        migrations.AddField(
            model_name='experience_title_en',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='主題名稱'),
        ),
    ]
